# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_main.ui'
#
# Created: Wed Feb 18 13:45:50 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1492, 536)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMinimumSize(QtCore.QSize(640, 480))
        self.frame.setMaximumSize(QtCore.QSize(640, 480))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.videoLive = QtWidgets.QWidget(self.frame)
        self.videoLive.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.videoLive.setMinimumSize(QtCore.QSize(640, 480))
        self.videoLive.setMaximumSize(QtCore.QSize(640, 480))
        self.videoLive.setObjectName("videoLive")
        self.horizontalLayout_6.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setMinimumSize(QtCore.QSize(640, 480))
        self.frame_2.setMaximumSize(QtCore.QSize(640, 480))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.videoFiltered = QtWidgets.QWidget(self.frame_2)
        self.videoFiltered.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.videoFiltered.setMinimumSize(QtCore.QSize(640, 480))
        self.videoFiltered.setMaximumSize(QtCore.QSize(640, 480))
        self.videoFiltered.setObjectName("videoFiltered")
        self.horizontalLayout_6.addWidget(self.frame_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.label_Status = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Status.sizePolicy().hasHeightForWidth())
        self.label_Status.setSizePolicy(sizePolicy)
        self.label_Status.setObjectName("label_Status")
        self.verticalLayout_3.addWidget(self.label_Status)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(-1)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_Filter1 = QtWidgets.QCheckBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Filter1.sizePolicy().hasHeightForWidth())
        self.checkBox_Filter1.setSizePolicy(sizePolicy)
        self.checkBox_Filter1.setSizeIncrement(QtCore.QSize(0, 0))
        self.checkBox_Filter1.setObjectName("checkBox_Filter1")
        self.horizontalLayout_3.addWidget(self.checkBox_Filter1)
        self.label_Filter1Name = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Filter1Name.sizePolicy().hasHeightForWidth())
        self.label_Filter1Name.setSizePolicy(sizePolicy)
        self.label_Filter1Name.setObjectName("label_Filter1Name")
        self.horizontalLayout_3.addWidget(self.label_Filter1Name)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_Filter2 = QtWidgets.QCheckBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Filter2.sizePolicy().hasHeightForWidth())
        self.checkBox_Filter2.setSizePolicy(sizePolicy)
        self.checkBox_Filter2.setObjectName("checkBox_Filter2")
        self.horizontalLayout_5.addWidget(self.checkBox_Filter2)
        self.label_Filter2Name = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Filter2Name.sizePolicy().hasHeightForWidth())
        self.label_Filter2Name.setSizePolicy(sizePolicy)
        self.label_Filter2Name.setObjectName("label_Filter2Name")
        self.horizontalLayout_5.addWidget(self.label_Filter2Name)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_Filter3 = QtWidgets.QCheckBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Filter3.sizePolicy().hasHeightForWidth())
        self.checkBox_Filter3.setSizePolicy(sizePolicy)
        self.checkBox_Filter3.setObjectName("checkBox_Filter3")
        self.horizontalLayout_4.addWidget(self.checkBox_Filter3)
        self.label_Filter3Name = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Filter3Name.sizePolicy().hasHeightForWidth())
        self.label_Filter3Name.setSizePolicy(sizePolicy)
        self.label_Filter3Name.setObjectName("label_Filter3Name")
        self.horizontalLayout_4.addWidget(self.label_Filter3Name)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_Status.setText(_translate("Dialog", "This is status text!!!"))
        self.checkBox_Filter1.setText(_translate("Dialog", "Enable"))
        self.label_Filter1Name.setText(_translate("Dialog", "Filter 1 Name"))
        self.checkBox_Filter2.setText(_translate("Dialog", "Enable"))
        self.label_Filter2Name.setText(_translate("Dialog", "Filter 2 Name"))
        self.checkBox_Filter3.setText(_translate("Dialog", "Enable"))
        self.label_Filter3Name.setText(_translate("Dialog", "Filter 3 Name"))

